@isTest
global class AddressComponentCalloutMock implements HttpCalloutMock {
    // Implement this interface method
    global HTTPResponse respond(HTTPRequest request) {
        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('{"status":"OK","predictions":[{"description":"Paris, France","distance_meters":8030004,"id":"691b237b0322f28988f3ce03e321ff72a12167fd","matched_substrings":[{"length":5,"offset":0}],"place_id":"ChIJD7fiBh9u5kcRYJSMaMOCCwQ","reference":"CjQlAAAA_KB6EEceSTfkteSSF6U0pvumHCoLUboRcDlAH05N1pZJLmOQbYmboEi0SwXBSoI2EhAhj249tFDCVh4R-PXZkPK8GhTBmp_6_lWljaf1joVs1SH2ttB_tw","terms":[{"offset":0,"value":"Paris"},{"offset":7,"value":"France"}],"types":["locality","political","geocode"]}]}');
        response.setStatusCode(200);
        return response; 
    }
}