//----------------------------------------------------------
//Author: Debarun
//Purpose: Test class for SetUpAuditTrailController
//********changes logs*********
//-------------------------------------------------------
@IsTest
private class SetUpAuditTrailControllerTest{

    private testmethod static void testmethod1(){
      Test.starttest();
      SetUpAuditTrailController.findFilters();
      test.stoptest();
    }

}