//----------------------------------------------------------
//Author: Debarun
//Purpose: Test class for SK_SetUpAuditTrailController
//********changes logs*********
//-------------------------------------------------------
@IsTest
private class SK_SetUpAuditTrailControllerTest{

    private testmethod static void testmethod1(){
      Test.starttest();
      SK_SetUpAuditTrailController.findFilters();
      test.stoptest();
    }

}